when@prod: &prod
    sulu_http_cache:
        tags:
            enabled: false
        cache:
            max_age: 3600
            shared_max_age: 3600
        proxy_client:
            symfony:
                enabled: false # disable this when varnish is used

    # Varnish Configuration:
    #
    # See: https://docs.sulu.io/en/2.0/cookbook/caching-with-varnish.html
    # Changes in the public/index.php is needed to disable the symfony http cache and use varnish instead
    #
    #        varnish:
    #            enabled: true
    #            servers:
    #                - '%env(resolve:VARNISH_SERVER)%''

when@stage: *prod
